[package]
name = "battleship"
version = "0.2.0"
authors = ["Pierre Gimalac <pierre.gimalac@gmail.com>"]
edition = "2018"

[dependencies.sdl2]
git = "https://github.com/AngryLawyer/rust-sdl2"
default-features = false
features = ["ttf"]

[dependencies]
rand = ""
